plugins:
  - '../../openapi/plugins/docs-plugin.js'
extends:
  - recommended
  - docs/all
x-influxdata-product-name: InfluxDB 3 Enterprise 

apis:
  v3@3:
    root: v3/ref.yml
    x-influxdata-docs-aliases:
      - /influxdb3/enterprise/api/
